DEBUG: 0
MAX_STEPS: 1

USE_FIXED_MOVABLES: 1

BOUNDARY: 
  LEFT: -1.
  RIGHT: 1.
  UP: -1.
  DOWN: 1.

NUM_MOVABLES: 3
COLLISION_DIST: 0.15
REACHABLE_DIST: 0.4

# NUM_MOVABLES: 1
# COLLISION_DIST: 0.3
# REACHABLE_DIST: 0.6
