!include arm_env.yaml

DEBUG: 0

TASK_LEVEL: 3

MAX_STEPS: null

OBSERVATION:
  TYPE: 'point_cloud'
  NUM_POINTS: 1024

ACTION:
  TYPE: 'CUBOID'

  # The `GRASP` defines a cuvoid region for the grasping center.
  GRASP:
    LOW: [0.30, -0.30, 0.02]
    HIGH: [0.90, 0.30, 0.12]

  TASK:
    T: 8
    LOW:  [0.60, 0.00, 0.02, 0.00]
    HIGH: [1.50, 0.50, 0.50, 6.29]

  KEYPOINTS:
    NUM: 2
    
SIM:
  ARM:
    CONFIG: 'configs/robots/sawyer.yaml'
    POSE: [[0, 0, 0], [0, 0, 0]]

  GROUND:
    PATH: 'data/sim/planes/plane.urdf'
    POSE: [[0, 0, -0.9], [0, 0, 0]]

  TABLE:
    PATH: 'data/sim/tables/table_grasp.urdf'
    POSE: [[0.6, 0, 0], [0, 0, 0]]

  GRASPABLE:
    PATHS: [
      'data/sim/train/*/*/*.urdf'
      ]
    TEST_PATHS: [
      #'data/sim/test/hard/*/*.urdf'
      'datagen/part/head/body.urdf'
      ]
    POSE:
      X: 0.1
      Y: -0.2
      Z: 0.3
      ROLL: [0, 6.28]
      PITCH: [0, 6.28]
      YAW: [0, 6.28]
    SCALE:
      [1.0, 1.0]
    USE_RANDOM_SAMPLE: 1
    RESAMPLE_N_EPISODES: 1

  SLOT_PATH: 'data/sim/envs/tool_hammer/slot_hard.urdf'
  PEG_PATH: 'data/sim/envs/tool_hammer/peg_hard.urdf'

  SLOT_OFFSET: -0.14
  HAMMER_HEIGHT_OFFSET: 0.115
 
  Z_OFFSET: 0.1


  MAX_ACTION_STEPS: 4000
