DEBUG: True

MAX_STEPS: 6

STEPS_CHECK: 100

CSPACE:
  LOW: [-0.4, -0.4]
  HIGH: [-0.4, 0.4]

ACTION:
  NUM_MODES: 2
  NUM_WAYPOINTS: 5
  POSITION_STEP: 0.1
  EULER_STEP: 0.31416
  WAYPOINT_TIME: 0.1

GROUND:
  PATH: 'data/sim/envs/mjolnir/plane.urdf'
  POSE: [[0, 0, 0], [0, 0, 0]]

WALL:
  PATH: 'data/sim/envs/mjolnir/wall.urdf'
  POSE: [[0, 0, 0], [0, 0, 0]]

MJOLNIR:
  POSE:
    X: [-0.4, 0.4]
    Y: [-0.4, 0.4]
    Z: 0.2
    ROLL: 0.0
    PITCH: 0.0
    YAW: [0, 3.14]
  MARGIN: 0.05

CONCAVE:
  PATH: 'data/sim/envs/mjolnir/concave.urdf'
  POSE:
    X: [-0.4, 0.4]
    Y: [-0.4, 0.4]
    Z: 0.2
    ROLL: 0.0
    PITCH: 0.0
    YAW: [0, 3.14]
  MARGIN: 0.05

CONVEX:
  PATH: 'data/sim/envs/mjolnir/convex.urdf'
  POSE:
    X: [-0.4, 0.4]
    Y: [-0.4, 0.4]
    Z: 0.2
    ROLL: 0.0
    PITCH: 0.0
    YAW: [0, 3.14]
  MARGIN: 0.05
