DEBUG: 0

NUM_MOVABLES: 3
COLLISION_DIST: 0.15
REACHABLE_DIST: 0.4


ACTION:
  NUM_MODES: 3


NUM_SAMPLES: 1024
NUM_STEPS: null


# Network
DIM_Z: 128
DIM_Z_FC: 256
DIM_STATE_FC: 256
DIM_START_POSITION_FC: 256
DIM_MODE_FC: 256
