DEBUG: 1


# TASK_NAME: null
# TASK_NAME: 'gather'
# TASK_NAME: 'insert'
TASK_NAME: 'cross'


BATCHED: 1


ACTION:
  CSPACE:
    LOW: [0.3, -0.4, 0.115]
    HIGH: [0.8, 0.4, 0.115]

  NUM_WAYPOINTS: 5

  MOTION:
    TRANSLATION_X: 0.04
    TRANSLATION_Y: 0.04
    ROTATION: 0.31416
    TIME: 0.1

  MIN_DELTA_POSITION: 0.01
  MIN_DELTA_ANGLE: 0.01

  USE_PRIMITIVE: 1


HEURISTICS:
  MAX_ATTEMPS: 2000


# Network
USE_POINT_CLOUD: false

DIM_C: 32
DIM_Z: 32

DIM_FC_C: 128
DIM_FC_Z: 128
DIM_FC_STATE: 64
DIM_FC_ACTION: 64


# Sampling
NUM_SAMPLES: 512
NUM_C_ELITES: 4
NUM_STEPS: 5

USE_LATENT_ACTION: 1
USE_HEURISTICS_SAMPLER: 0
USE_RULE_BASED_FILTER: 0
NETWORK: 'PushSMPC'
# NETWORK: 'PushGMPC'
