DEBUG: 0


ACTION:
  CSPACE:
    LOW: [0.3, -0.4, 0.025]
    HIGH: [0.8, 0.4, 0.035]

  NUM_MODES: 3
  NUM_START_ANGLES: 8
  NUM_WAYPOINTS: 5

  MOTION:
    TRANSLATION_X: 0.04
    TRANSLATION_Y: 0.04
    ROTATION: 0.31416
    TIME: 0.1

  MIN_DELTA_POSITION: 0.01
  MIN_DELTA_ANGLE: 0.01

  USE_MODE: 1


HEURISTICS:
  MIN_DIST: 0.02
  MAX_DIST: 0.3
  TOOL_LENGTH: 0.2
  MAX_ATTEMPS: 2000


# Network
DIM_MODE_FC: 64
DIM_STATE_FC: 64
DIM_START_POSITION_FC: 64
DIM_START_ANGLE_FC: 64
DIM_MOTION_FC: 64
DIM_Z: 64


# Sampling
NUM_SAMPLES: 1024
NUM_STEPS: 1

USE_RULE_BASED_FILTER: 0

USE_LATENT_ACTION: 0
NETWORK: 'ToyLDM'

# USE_LATENT_ACTION: 1
# NETWORK: 'ToySLDM'

TASK_NAME: null
